[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "fa102907c5fe253e4ae473d04cd530d13a8a3549"
os = "macos"

    [[OpenCL.download]]
    sha256 = "d69c415b20a1f09ad7c8152c561005033be89b4d8ca6bab20d0278f925ed7893"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.aarch64-apple-darwin.tar.gz"
[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "3ba3a235268c75d4d722743d43d0134f46c769c3"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "2bb578fb41993bdd139b31a6a4bbc2641ce2c8361fcb10657d40d06701754d0a"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.aarch64-linux-gnu.tar.gz"
[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "c67379b851533c0d6d1bb62b271a7cfd8429a684"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "bd80ae68484cbff1a9a1fb88d2d0d87370cee689d4b1ad7c260d81dfef443378"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.aarch64-linux-musl.tar.gz"
[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "8f1c7fb81b4a0919bf119a9e66b210b47ed7ccb8"
os = "freebsd"

    [[OpenCL.download]]
    sha256 = "fd6b33b22755be078b83d5606e333d964eb6936d8758b7ada1229e54177654d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.aarch64-unknown-freebsd.tar.gz"
[[OpenCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "19dad7b0c09a96099e7eb8caeb5e7e6eba3d79df"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "95cb9977f2d7b3bd49214cb33a217be8df1bcf21e0beece2ea4755a9ecf61bab"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.armv6l-linux-gnueabihf.tar.gz"
[[OpenCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8dd7733a954b3f8fd24d2e6f654ab0ec665b3e48"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "375ae5353676ab129986eacf4af5ff38e532361c8f83bec761366c574701ca4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.armv6l-linux-musleabihf.tar.gz"
[[OpenCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0741091573fd795225ffbd60d817722a2632bd9"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "2e438f979b0e0ad521aec71abcc3d877cf793d91b7caeddbc84516bd89b36f92"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.armv7l-linux-gnueabihf.tar.gz"
[[OpenCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e4096aadd3f165f92f8787442f2664232ffa525"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "a2fd81f5af3290c86eb9b6d39cd1cdd35cbd2545bddf475150521a0c052cc0a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.armv7l-linux-musleabihf.tar.gz"
[[OpenCL]]
arch = "i686"
git-tree-sha1 = "18f5e2e3e2b5299f912d7094c78fdcbdf7a014bd"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "82e7646c33134b42193bd7dc91387874ddf5bbdb20fc369e1e6cb581d48717fd"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.i686-linux-gnu.tar.gz"
[[OpenCL]]
arch = "i686"
git-tree-sha1 = "7ede88c2087aaedb0d6445d58ecc7512a5caea89"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "33d727224756977ff4d2fda3c7869ab8295faf240251bcb0a29dc5c6852c98b1"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.i686-linux-musl.tar.gz"
[[OpenCL]]
arch = "i686"
git-tree-sha1 = "e8eb6c6efe37f640c9ef5d26d9be55498dbd75c2"
os = "windows"

    [[OpenCL.download]]
    sha256 = "0919ebaf8a45ea893296f26feb048baf395ea7a08c47c4fadb8758f778b516c0"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.i686-w64-mingw32.tar.gz"
[[OpenCL]]
arch = "powerpc64le"
git-tree-sha1 = "0a448d759b5115d356f43ecd47f55407e5994ed8"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "a381998f3ce366d03cb6c5cafb2bce54f6e9b07a8130c019637c2fe16668534c"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.powerpc64le-linux-gnu.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "9ea21334258e78539c0eca4ae5e0210609db4242"
os = "macos"

    [[OpenCL.download]]
    sha256 = "b6c2a0e844cb07f829105970587d50f949c476ff1560f29a324b771202227961"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.x86_64-apple-darwin.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "98a96034f0c7be043f08b162828add4f1169813c"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "9f5c19b01441cddf9ad899322fe535285ee82b0afa772882210449d4a9beeb65"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.x86_64-linux-gnu.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "f667e320441b6061ae3d0df685a0086be7a9c9e6"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "4fc52667f67e341e4d05595438a2e55e41e416f7f873fa3a70d534838df7f411"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.x86_64-linux-musl.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "22531acea5f810dbc374d61ab1fbc5c8caceb065"
os = "freebsd"

    [[OpenCL.download]]
    sha256 = "1d4945b47cccc1c103e1fa7b0b718cd5408e606331e9de714ea0d4818e07cb95"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.x86_64-unknown-freebsd.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "00fc848513878811a88cb26f674b9cdf32c099f0"
os = "windows"

    [[OpenCL.download]]
    sha256 = "e6f0a08246293015fcac4df900fd00c4706e848b5c293838b8b98ec73ec8f660"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2024.10.24+0/OpenCL.v2024.10.24.x86_64-w64-mingw32.tar.gz"
