[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "04e4a25abc701f2f495c18e32492a066022559db"
os = "macos"

    [[OpenCL.download]]
    sha256 = "41dc5c2055a766609dd3f078086b487f855ff16480fe64fa85f27607529a530c"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.aarch64-apple-darwin.tar.gz"
[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "8ae61e26711b7e075298ae120ae8da33c019eeac"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "678ff4bdb14bf16b19a1f1fb68b7703db758a0dd41ba21a6fe41175b5d3131ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.aarch64-linux-gnu.tar.gz"
[[OpenCL]]
arch = "aarch64"
git-tree-sha1 = "f5a873060d4fa35cabcd443329403618d9945718"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "9acc781b486cb1a09e2ef1aa4146cf56e3da5eaeb6f0db9d0d51211a5061093e"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.aarch64-linux-musl.tar.gz"
[[OpenCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd8e7fcf031d179f20e14e34d94c393b8bf4746c"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "d52f5d64630532ce240163c903b1f573d4848875eab0f31c50d5452a606888fc"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.armv6l-linux-gnueabihf.tar.gz"
[[OpenCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11642a8b72480d6941318fba2ee5c579fe21890d"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "f00801538448b288eafad3836115ea78fb7c828d49434edceaafc1f43dcc908f"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.armv6l-linux-musleabihf.tar.gz"
[[OpenCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2928cf23f43cddeefae82a72190d352e626583eb"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "82080dae90dbb4f36504a4a6c05e24aa11ede0e0f7f2a8b51192fdfb44045d50"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.armv7l-linux-gnueabihf.tar.gz"
[[OpenCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c443583e5a45d0157a9765f8fe09483048909e7"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "58ec7e182339520ad55e4b3a660806109f3b599d4c88414d6a316dc5e19f6844"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.armv7l-linux-musleabihf.tar.gz"
[[OpenCL]]
arch = "i686"
git-tree-sha1 = "568abce3eb0baa528a34d5dac1a8742e63974bff"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "fb368ead944ec528b8d6cf96b2fc1cc1d0c9088c4bf9f8f79f9fdd4f68eb8ef6"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.i686-linux-gnu.tar.gz"
[[OpenCL]]
arch = "i686"
git-tree-sha1 = "bc987a3caa04bd9869e9ae78ea31d5195c4e8496"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "ed02c80fdb94474cbde7530e32a7dc4fa2a78a46deaf8bd0d6f218738490b03f"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.i686-linux-musl.tar.gz"
[[OpenCL]]
arch = "powerpc64le"
git-tree-sha1 = "290d6638f8b76b448c3726e344635a2c4da382a4"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "4c9b4d02f4fca35b48e37d3b6e16e65f0dd0c41e4152419abfa86452aef90054"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.powerpc64le-linux-gnu.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "6bf23195ed42b12e0234e37be298a4571d753c97"
os = "macos"

    [[OpenCL.download]]
    sha256 = "af8e6c8c0e17da5e1b21172bbfb9529134db480863c49c9c250d1520758612c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.x86_64-apple-darwin.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "113cdfb400110abbe4d925555e393c8501a9b71c"
libc = "glibc"
os = "linux"

    [[OpenCL.download]]
    sha256 = "e1d622cd46f3171f28a4687199ecd5524f19335d2349902ef7bbf7cb94526961"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.x86_64-linux-gnu.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "793055e5aea68f65e6446faec8b2c1637d67943b"
libc = "musl"
os = "linux"

    [[OpenCL.download]]
    sha256 = "334fda772dc9ff6afd76c720c090dd96bfb6b2f4697efa7e57a69dc99b0d4885"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.x86_64-linux-musl.tar.gz"
[[OpenCL]]
arch = "x86_64"
git-tree-sha1 = "4063112fcf8b15463b2c995fedaa19feb878bacb"
os = "freebsd"

    [[OpenCL.download]]
    sha256 = "34bf6e0c8556b846f67fedd7f072d438dd30e821af7eb8e7eed33eae2e08e7eb"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_jll.jl/releases/download/OpenCL-v2023.12.14+0/OpenCL.v2023.12.14.x86_64-unknown-freebsd.tar.gz"
