# Autogenerated wrapper script for OpenCL_jll for i686-w64-mingw32
export libopencl

JLLWrappers.@generate_wrapper_header("OpenCL")
JLLWrappers.@declare_library_product(libopencl, "OpenCL.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libopencl,
        "bin\\OpenCL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
    global drivers = String[]

end  # __init__()
